### ISSUE TITLE
Could you provide files mentioned in settings.json? or How to generate them? Thanks!

### ISSUE THREAD

**Issue by guyucowboy** [EliasVansteenkiste/dsb3#4]
Hi, EliasVansteenkiste,
Your work is great. Thanks for sharing！
I download this excellent project，and it seems that the code(make_final_split.py) could not run if some files could not find mentioned in pathfinder.py . For example, test_labels.csv, dsb_validation_split.pkl, final_split.pkl, validation_split.pkl, dsb_validation_lb_mixed_split.pkl, annotations_extended_mixed.csv.
Could you provide them, or how can I generate them？
Thanks for your help in advance！
Gu Yu

**Comment by EliasVansteenkiste** [comment]
Hi guyucowboy,
I committed the meta data files to the master branch.
That should help you further. See commit 4489113a3a397ed85fe81a4d2d5252da6be1763a.

**Comment by guyucowboy** [comment]
Hi, EliasVansteenkiste,
Thanks for your reply!
Then, I use the command: python train_seg_patch.py luna_p8a1
I got an error at line:

iter_train = theano.function([idx], train_loss, givens=givens_train, updates=updates):

Traceback (most recent call last):
  File "D:\software\JetBrains\PyCharm 2017.1.1\helpers\pydev\pydevd.py", line 1578, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\software\JetBrains\PyCharm 2017.1.1\helpers\pydev\pydevd.py", line 1015, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\software\JetBrains\PyCharm 2017.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "G:/pythonproject/pycharm/kaggle/EliasVansteenkiste-dsb3-master/dsb3-master/train_seg_patch.py", line 83, in <module>
    iter_train = theano.function([idx], train_loss, givens=givens_train, updates=updates)
  File "D:\software\Anaconda3\envs\lungSegCondaEnvX\lib\site-packages\theano\compile\function.py", line 326, in function
    output_keys=output_keys)
  File "D:\software\Anaconda3\envs\lungSegCondaEnvX\lib\site-packages\theano\compile\pfunc.py", line 449, in pfunc
    no_default_updates=no_default_updates)
  File "D:\software\Anaconda3\envs\lungSegCondaEnvX\lib\site-packages\theano\compile\pfunc.py", line 219, in rebuild_collect_shared
    cloned_v = clone_v_get_shared_updates(v, copy_inputs_over)
  File "D:\software\Anaconda3\envs\lungSegCondaEnvX\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "D:\software\Anaconda3\envs\lungSegCondaEnvX\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "D:\software\Anaconda3\envs\lungSegCondaEnvX\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "D:\software\Anaconda3\envs\lungSegCondaEnvX\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "D:\software\Anaconda3\envs\lungSegCondaEnvX\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "D:\software\Anaconda3\envs\lungSegCondaEnvX\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "D:\software\Anaconda3\envs\lungSegCondaEnvX\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "D:\software\Anaconda3\envs\lungSegCondaEnvX\lib\site-packages\theano\compile\pfunc.py", line 93, in clone_v_get_shared_updates
    clone_v_get_shared_updates(i, copy_inputs_over)
  File "D:\software\Anaconda3\envs\lungSegCondaEnvX\lib\site-packages\theano\compile\pfunc.py", line 96, in clone_v_get_shared_updates
    [clone_d[i] for i in owner.inputs], strict=rebuild_strict)
  File "D:\software\Anaconda3\envs\lungSegCondaEnvX\lib\site-packages\theano\gof\graph.py", line 238, in clone_with_new_inputs
    new_inputs[i] = curr.type.filter_variable(new)
  File "D:\software\Anaconda3\envs\lungSegCondaEnvX\lib\site-packages\theano\tensor\type.py", line 235, in filter_variable
    self=self))
TypeError: Cannot convert Type TensorType(float32, 5D) (of Variable Subtensor{int64:int64:}.0) into Type TensorType(float32, (False, True, False, False, False)). You can try to manually convert Subtensor{int64:int64:}.0 into a TensorType(float32, (False, True, False, False, False)).

I do not know how to fix it. I use python3(I change the code alittle to python3 ), theano 0.9, Lasagne-0.2.dev1.
Thanks again for your help!

**Comment by guyucowboy** [comment]
Hi, EliasVansteenkiste,
what is the version of the theano and lasagne?
Thanks!
